prax-wallet/prax

- apps/extension/src/routes/popup/approval/origin.tsx
- apps/extension/src/shared/components/display-origin-url.tsx
- packages/ui/components/ui/box.tsx
- packages/ui/components/ui/tx/view/viewbox.tsx
Closes #1219
Fixes the animations from the mentioned issue. Plus, it deals with annoying development artifact – a red scrollbar in the extension connection popup.
> fix: #1219: extension animations

- apps/extension/src/routes/popup/approval/approve-deny.tsx
- apps/extension/src/routes/popup/approval/use-window-countdown.ts
Closes #40 
When the window is out of focus, approval countdown freezes. When the focus is back, countdown restarts from the beginning
> fix(extension): #40: pause ApproveDeny component when out of focus

- .firebaserc
- .github/workflows/deploy-firebase.yml
- firebase.json
Restores some crucial Firebase configs to straighten out the CD pipeline for updating the prax marketing website, hosted on Firebase. Uses a custom runner, to reduce job time from ~12m on ubuntu-latest to ~5m on the faster version.
> ci: fix prax website deploy

- apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/use-grpc-endpoint-form.ts
Closes #37 
Add a loader to the RPC selection setting page
> fix(extension): #37: add loader to rpc validation

- apps/extension/src/routes/popup/settings/settings.tsx
Instead of a re-direct to the login page, this instead closes the popup (as it resets). See code comment for reasoning.
> Reload ext on logout

- apps/extension/src/routes/popup/settings/settings-passphrase.tsx
**Context:** Settings page, after submitting their password to reveal their seed phrase
This PR sets the react state to an empty string if successful. That way, when the seed phrase is revealed, the users plain text password is not still in memory.
It is quite the edge case (given memory is flushed every time someone clicks away from the popup), but auditors feel it's best to clear it manually as extracting plain text passwords have security implications for the user outside of Prax.
> Clear password in memory (settings page)

- .changeset/green-frogs-shake.md
- apps/extension/src/wallet-services.ts
at some point saving app params to local was removed.
this restores ability to operate offline.
edit: fixes #32 
accidentally duplicating work in #64
> save app params

- apps/extension/src/routes/page/onboarding/set-grpc-endpoint.tsx
- apps/extension/src/routes/popup/settings/settings-rpc.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/use-grpc-endpoint-form.ts
This PR doesn't fix `fixEmptyGrpcEndpointAfterOnboarding`, only the bug with custom RPC when onboarding
> Fix onboarding for custom RPCs

- packages/ui/components/ui/tx/actions-views/undelegate.tsx
Syncs Prax TX display with Penumbra, copies https://github.com/penumbra-zone/web/pull/1384
> feat(ui): display epoch index in undelegate transaction action

- apps/extension/src/shared/components/default-frontend-form/index.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
Fixes edge case where entering a custom RPC URL with a trailing slash will result in links in other parts of the app being broken.
@grod220 I couldn't find a corresponding test file for this form - should I create one?
> fix: trim trailing slash from custom rpc url

- .changeset/serious-crews-dream.md
- apps/extension/src/routes/page/onboarding/generate.tsx
Previously, you could click the (blurred-out) "Copy" button for the seed phrase even before you'd clicked "Reveal". This fixes that.
Closes #73
> Disable the Copy button for the seed phrase until it's revealed

- packages/ui/components/ui/block-sync-status/hooks.ts
fixes https://github.com/penumbra-zone/web/issues/1233
This constraints the sync estimate text to at most two largest units. This means that instead of "5 days, 3 hours, 10 minutes and 3 seconds" this will show "5 days and 3 hours", or "13 minutes, 44 seconds" etc.
> fix: shorten sync time to at most two units

- apps/extension/package.json
- apps/extension/src/content-scripts/injected-penumbra-global.ts
- pnpm-lock.yaml
this PR fulfills the interface defined in https://github.com/penumbra-zone/web/pull/1420
published versions of the client package now expect this interface to be fulfilled
the react wrapper also depends on this interface
> fulfill injection state interfaces

- apps/extension/public/manifest.json
content scripts injected to http never actually achieved sentience, but they should probably still be restricted to https.
> only inject to https

- .github/workflows/turbo-ci.yml
- apps/extension/src/routes/page/onboarding/set-password.tsx
- apps/extension/src/routes/page/restore-password/set-password.tsx
This pull request fix: https://github.com/prax-wallet/web/issues/80
https://github.com/user-attachments/assets/0b44f688-df9c-49f0-94d9-26f7465752d0
> fix: bug pressing enter not working in reset password

- packages/ui/components/ui/box/index.tsx
WIP: waiting on @jessepinho to confirm the parent-box layout animation doesn't break anything.
fixes #78
> fix: don't auto-animate children of box

- apps/extension/src/routes/popup/settings/settings-connected-sites/known-site.tsx
> fix(extension): #118: truncate the URL of connected sites

- .github/workflows/turbo-ci.yml
- README.md
- apps/extension/webpack.config.ts
- package.json
- pnpm-lock.yaml
- scripts/add-tgz.ts
tgz reloader was originally written to watch normal `dependencies`, but will now also watch `devDependencies` and the `pnpm.overrides` that are used since add:tgz was added
see the updated readme https://github.com/prax-wallet/web/blob/ad4807dd0bab00bd12d34948ac76f93b4f6df026/README.md
> tgz reload will now watch pnpm overrides

- apps/extension/public/manifest.json
- apps/extension/src/senders/validate.ts
Closes #107 
1. Changes to the manifest to inject content scripts into http://localhost
2. Changes to the `assertValidSender` function to allow http://localhost
> fix(extension): #107: allow http for localhost

- apps/extension/package.json
- apps/extension/public/manifest.json
- apps/extension/src/senders/validate.ts
Reverts prax-wallet/web#129
@VanishMax looks like this change is not allowed by the chrome dev dashboard. Reverting for now to unblock release.
> Revert "fix(extension): #107: allow http for localhost"

- .github/workflows/extension-upload.yml
> crx release workflow `NODE_ENV='production'`

- apps/extension/src/content-scripts/injected-penumbra-global.ts
temporary fix to mitigate missing request method
> inject request method

- .github/workflows/extension-upload.yml
Dev deps required for post install. Not being installed after https://github.com/prax-wallet/web/pull/170.
Overriding in the github action. Perhaps there's a more proper way here, but adding this for now to unblock release.
> Install devDeps as well

- apps/extension/src/content-scripts/injected-penumbra-global.ts
prevents issue that reverted #173
there may still be some way to trigger it, but both minifronts seem ok
>  inject request method without handling neutered port

- apps/extension/src/hooks/latest-block-height.ts
references https://github.com/prax-wallet/web/pull/164#discussion_r1739624507 cc @grod220 
based on offline discussion with @turbocrime, the channel transport has default [60 second timeout](https://github.com/penumbra-zone/web/blob/990291f6daef61bdb219f0c98bfbe481f25cfd83/packages/transport-dom/src/create.ts#L80), and grpc web transport have [no timeout](https://github.com/prax-wallet/web/blob/main/apps/extension/src/transport-options.ts#L4). The channel transport timeout is insufficient for our needs, as we may need to cycle through multiple rpcs to request the block height during onboarding. Instead, we’ve implemented a more granular request-level timeout of [5 seconds](https://github.com/prax-wallet/web/compare/channel-transport?expand=1#diff-1953ce36add59a143bebbfa0a7021d102fa0268e95a …
> onboarding: request level timeouts

- apps/extension/package.json
- apps/extension/public/manifest.json
prax has already consumed the latest versioned npm packages from https://github.com/penumbra-zone/web/pull/1765.
> prep v13.0

- apps/extension/src/hooks/numeraires-query.ts
- apps/extension/src/routes/page/onboarding/set-numeraire.tsx
- apps/extension/src/routes/popup/settings/settings-numeraires.tsx
- apps/extension/src/shared/components/numeraires-form.tsx
Bug fix. Now that a numeraire is [available in the registry](https://github.com/prax-wallet/registry/pull/94), Prax should be recognizing it and during onboarding, giving the users an opportunity to use it. This will enable usdc prices in minifront.
However, due to a react useEffect loading bug, it is skipping this step. This PR fixes that.
> Re-enable numeraires in onboarding

- .github/workflows/extension-upload.yml
- .gitignore
- apps/extension/.env
- apps/extension/.env.beta
- apps/extension/package.json
- apps/extension/public/beta-manifest.json
- apps/extension/src/utils/zip-extension.ts
- apps/extension/webpack.beta-config.ts
- apps/extension/webpack.config.ts
- apps/extension/webpack.prod-config.ts
- package.json
Relates to https://github.com/penumbra-zone/web/issues/1811
The extension relies on the `.env` file that sets the `PRAX` variable with the chrome extension ID. This ID is then used to correctly inject the provider to web pages. The build process didn't consider it, and the BETA extension injected the prod ID. The `client` package, in its turn, always checks the injected id matches chrome manifest to avoid security breaches, – it all means the BETA package didn't work completely.
This PR fixes the issue with BETA extension not being built correctly:
- Separates webpack bundles into the `prod` and `beta` versions
- Removes the `.env` files in favor of string replacements
- Beta bundle produces the `beta-dist` directory
- Beta bundle also modifies the `manifest.json` file to update favicons …
> fix: beta extension bundle

- apps/extension/src/routes/page/onboarding/set-grpc-endpoint.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
- apps/extension/src/shared/components/grpc-endpoint-form/use-grpc-endpoint-form.ts
- apps/extension/src/storage/onboard.ts
- apps/extension/src/wallet-services.ts
Suggestion for https://github.com/prax-wallet/prax/pull/216
`correctBirthdayHeightIfNeeded` would require unit tests though
> before hook suggestion

- packages/ui/components/ui/account-switcher/account-switcher.test.tsx
- packages/ui/components/ui/account-switcher/index.tsx
Closes #225 
Changes the `AccountSwitcher` component to display `sub-account` and `main account` terms instead of `account`.
Main Account             |  Sub-Account #0
:-------------------------:|:-------------------------:
I also thought about the successful onboarding page but decided not to change:
> fix(ui): #225: change 'account' to 'sub-account'

- apps/extension/src/routes/popup/approval/transaction/index.tsx
- packages/ui/components/ui/json-viewer/index.tsx
- packages/ui/components/ui/tx/index.tsx
second part of https://github.com/penumbra-zone/web/issues/1882
focused more on functionality rather than design, which definitely has room for improvement.
---------------------------
> prax: add non-native-fee-warning

- apps/extension/src/senders/validate.ts
Allows `http` apps to connect to production-built Prax
> fix: allow http for production prax too

- packages/query/package.json
- packages/query/src/block-processor.ts
- packages/query/src/helpers/identify-txs.test.ts
- packages/query/src/helpers/price-indexer.test.ts
- packages/query/src/helpers/process-action-dutch-auction-end.test.ts
- packages/query/src/helpers/skip-trial-decrypt.test.ts
- packages/query/src/queriers/app.ts
- packages/query/src/queriers/auction.ts
- packages/query/src/queriers/cnidarium.ts
- packages/query/src/queriers/compact-block.ts
- packages/query/src/queriers/ibc-client.ts
- packages/query/src/queriers/sct.ts
- packages/query/src/queriers/shielded-pool.ts
- packages/query/src/queriers/staking.ts
- packages/query/src/queriers/tendermint.ts
- packages/query/src/root-querier.ts
A follow up from https://github.com/prax-wallet/prax/pull/247
Legacy build methods causes the typescript compiler to create a bunch of compiled files locally. Also, fixes import paths that were throwing eslint errors after making the `lint` script the same as the other packages.
> Correct import paths

- packages/query/src/helpers/identify-txs.test.ts
- packages/query/src/helpers/identify-txs.ts
Closes https://github.com/prax-wallet/prax/issues/245
During sync, Prax currently stores MsgReceived in storage:
https://stake.with.starlingcyber.net/#/tx/fb5eaef8632baf0ef62e061e2cf8d0ab49b2f3b63385201fe21933f053cf23b5
But is not storing MsgAcknowledgement:
https://stake.with.starlingcyber.net/#/tx/295E9A9044CCA0F1869DD8AD80F51D9E997557832170F1EA1DA0AFE315AC35A4
or
MsgTimeout:
https://stake.with.starlingcyber.net/#/tx/A3A396E025D240A6502ED7122B424A84FFCEC4883360824727E06CB1FA84D213
Those are particularly relevant as users should be informed of when their IBC bounces back. This PR addresses this.
> Detect other relay actions

- .github/ISSUE_TEMPLATE/deployment.md
references https://github.com/prax-wallet/prax/issues/256
> chore: update release checklist

- .changeset/strong-carrots-protect.md
- apps/extension/src/routes/popup/home/assets-table.tsx
- apps/extension/src/routes/popup/home/index.tsx
- apps/extension/src/routes/popup/popup-layout.tsx
- packages/tailwind-config/index.ts
- packages/ui/components/ui/select/select-account.tsx
- packages/ui/components/ui/table/index.tsx
Closes #252 
Adds the asset table with balances per selected account. Empty if no balances are there for selected account.
> feat(extension): #252: asset list

- apps/extension/public/manifest.json
- apps/extension/src/service-worker.ts
uses [chrome.alarms](https://developer.chrome.com/docs/extensions/reference/api/alarms) API to restart the service worker after extended periods of inactivity and make sync progress over time without any frontend providers or the extension being opened. This ensures the chain is already synced when the user returns to penumbra after that extended period of not using it. We aptly name this '**idle syncing**'. 
- accompanying context doc: https://docs.google.com/document/d/18awgAeCIhwVLmfKj_R7pXoFTNtcOMtdtKhCWRs0iDgE/edit?tab=t.0
(this a long winded sanity check for sidestepping a major refactor to our connection lifecycle)
cc @hdevalence 
-------------------
when adding an event listener to log details as the alarm triggers (set `periodInMinutes` to 1 minute) and inspecting the service …
> feat: idle syncing

- packages/ui/components/ui/block-sync-status/index.tsx
replace illegible and unhelpful sync errors with a more human-readable error message.
pairs with https://github.com/penumbra-zone/web/pull/1997
---------
_before_
-----------
_after_
> prax: readable sync error message

- README.md
Capturing recent dev env setup, as explained by @TalDerei. See related discussion in historical PR [0]. Used these steps to test locally against the testnet, which is running an alpha version of LQT support [1]. I believe this docs update is sufficient to close [2].
[0] https://github.com/penumbra-zone/web/pull/1884#discussion_r1827439241
[1] https://github.com/penumbra-zone/penumbra/issues/5010
[2] https://github.com/prax-wallet/prax/issues/149
> docs: local build steps

- apps/extension/package.json
- apps/extension/public/beta-manifest.json
- apps/extension/public/manifest.json
bumps latest version to `v17.0` – major breaking change that's not backwards compatible
latest npm package deps were already published and updated in https://github.com/prax-wallet/prax/pull/292 and are currently up to date on this release branch
> prep v17.0

- package.json
- pnpm-lock.yaml
vitest requires a restricted version range of its `@vitest/browser` component installed as peer. this satisfies that
> chore: correct peer dep of vitest

- packages/ui/package.json
- pnpm-lock.yaml
dep `@textea/json-viewer` at 3.x wants peer `@mui/material` 5.x, but our dep is 6.x
`@textea/json-viewer` at 4.x matches our `@mui/material` dep, and the migration guide indicates no necessary change.
> chore: bump `@textea/json-viewer`

- apps/extension/package.json
- apps/extension/src/state/tx-approval.ts
- packages/context/package.json
- packages/ui/components/ui/tx/actions-views/isc20-withdrawal.tsx
- packages/ui/package.json
- pnpm-lock.yaml
requires bumping package deps to pass CI
corollary to https://github.com/penumbra-zone/web/issues/2023 and sparsely pairs with https://github.com/penumbra-zone/web/pull/2101
> prax: minimal t-addr reversion 

- apps/extension/package.json
- apps/extension/public/beta-manifest.json
- apps/extension/public/manifest.json
latest npm package deps were already published and updated in https://github.com/prax-wallet/prax/pull/297 and are currently up to date on this release branch
> prep v18.0.0

- .syncpackrc
- apps/extension/package.json
- apps/extension/src/clients.ts
- apps/extension/src/hooks/latest-block-height.ts
- apps/extension/src/routes/page/onboarding/password/utils.ts
- apps/extension/src/rpc/index.ts
- apps/extension/src/service-worker.ts
- apps/extension/src/shared/components/grpc-endpoint-form/use-grpc-endpoint-form.ts
- apps/extension/src/wallet-services.ts
- docs/extension-services.md
- package.json
- packages/context/package.json
- packages/query/package.json
- packages/query/src/queriers/app.ts
- packages/query/src/queriers/auction.ts
- packages/query/src/queriers/cnidarium.ts
- packages/query/src/queriers/compact-block.ts
- packages/query/src/queriers/funding.ts
- packages/query/src/queriers/ibc-client.ts
- packages/query/src/queriers/sct.ts
- packages/query/src/queriers/shielded-pool.ts
- packages/query/src/queriers/staking.ts
- packages/query/src/queriers/tendermint.ts
- packages/query/src/queriers/utils.ts
- packages/ui/package.json
- pnpm-lock.yaml
pins `@bufbuild/protobuf`, `@connectrpc/connect`, `@connectrpc/connect-web` to the specific versioned deps used in the web / dex repos as part of the migration. The former, `^1.x`, caused mismatched a peer deep resolution and was throwing connectrpc errors.
-------------
> synpack deps

- apps/extension/src/entry/popup-root.tsx
- apps/extension/src/state/index.ts
- apps/extension/src/state/origin-approval.test.ts
- apps/extension/src/state/origin-approval.ts
- apps/extension/src/state/tx-approval.test.ts
- apps/extension/src/state/tx-approval.ts
instead of handling message responders directly, popup slices simply provide a promise for their result. the responder function remains within the message listener scope.
tests are added to confirm functionality in the slices, then the change is implemented.
> refactor: popup slices use promises to respond

- .changeset/happy-needles-warn.md
- packages/ui/components/ui/tx/actions-views/liquidity-tournament-vote.tsx
- packages/ui/components/ui/tx/actions-views/output.tsx
- packages/ui/components/ui/tx/actions-views/spend.tsx
- packages/ui/components/ui/tx/actions-views/value-with-address.tsx
- packages/ui/components/ui/value/value.tsx
Closes https://github.com/penumbra-zone/web/issues/2235
Small changes for better display of action views in the old designs of the action views.
After the changes:
> fix(ui): #2235: approval dialog styles

- packages/query/src/helpers/identify-txs.ts
cleans up dead code from initial LQT implementation pass. Not sure why the linter didn't complain
> LQT: dead code removal

- apps/extension/package.json
- apps/extension/src/hooks/latest-block-height.ts
- apps/extension/src/routes/page/onboarding/password/utils.ts
- packages/context/package.json
- packages/ui/package.json
- pnpm-lock.yaml
defaults to the RC-hosted high-performance and reliable RPC `https://penumbra-1.radiantcommons.com/` during onboarding.
requires bumping the npm registry version to `12.7.0` after https://github.com/prax-wallet/registry/pull/142 lands to pass CI.
---------------
> registry: default rpc selection

- apps/extension/src/routes/page/onboarding/generate.tsx
references https://github.com/prax-wallet/prax/issues/351
Importantly, there's a dependency here for implementing a reminder prompting users to back up their seed phrase the first time prax is opened in the next accompanying release. 
-----------------------------
https://github.com/user-attachments/assets/e2d0a17a-ebc8-40d9-ac24-e84e73092025
> onboarding: remove seed phrase game for freshly generated wallets

- apps/extension/src/routes/page/onboarding/generate.tsx
- apps/extension/src/routes/popup/settings/settings-passphrase.tsx
`navigateToPasswordPage` mounts and runs immediately, right after the call to generate the phrase. This separates that logic and blocks redirection until the phrase is generated.
> seed phrase: seperate generation and navigation logic

- .github/workflows/extension-upload.yml
Partial reversion of 5b01bf98bf9e74eb421bb8b829148cdbdfe7c7df, from PR #378. Keeps the relocated GHA references, drops the draft release object, as we prefer the old-style changelogs.
> ci: don't create draft release objects

- apps/extension/src/state/index.ts
- apps/extension/src/state/password.test.ts
- apps/extension/src/state/password.ts
- apps/extension/src/state/persist.ts
- apps/extension/src/state/wallets.ts
zustand persist is slightly broken, with some misnamed keys
just drop the session persist, which never worked. use the typed listener provided by `ExtensionStorage` wrapper.
drop unused password key from zustand.
this is split out from https://github.com/prax-wallet/prax/pull/390
> Clean up storage/zustand persist

- apps/extension/src/ctx/authorization.ts
- apps/extension/src/routes/popup/approval/approve-deny.tsx
- apps/extension/src/routes/popup/approval/transaction/index.tsx
- apps/extension/src/routes/popup/approval/transaction/use-transaction-view-switcher.ts
- apps/extension/src/state/origin-approval.ts
- apps/extension/src/state/tx-approval.test.ts
- apps/extension/src/state/tx-approval.ts
- apps/extension/src/state/tx-validation/assert-valid-plan.test.ts
- apps/extension/src/state/tx-validation/assert-valid-plan.ts
instead of performing plan validation inside the custody service before creating UI, perform validation within the approval slice and display validation failures for inspection.
> feat: perform visible transaction validation
