apps/extension/src/listeners/message-external.ts

Simplify ext-connectable easter egg

---

packages/ui/components/ui/tx/actions-views/isc20-withdrawal.tsx

Closes #76 
Renders date and time in the following way:

fix(ui): show timeoutTime in UTC

---

package.json

restore watch script

---

.changeset/eight-ducks-search.md
.changeset/long-bees-unite.md
.changeset/serious-crews-dream.md
apps/extension/CHANGELOG.md
apps/extension/package.json
apps/extension/public/manifest.json
packages/context/CHANGELOG.md
packages/context/package.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json

Related to: https://github.com/prax-wallet/web/issues/101

Prep v11.4.0 release

---

README.md
docs/deployment.md
docs/testing.md

fixes https://github.com/prax-wallet/web/issues/47

docs: update documentation

---

apps/extension/package.json
apps/extension/src/shared/components/default-frontend-form/index.tsx
apps/extension/src/shared/components/grpc-endpoint-form/index.tsx
packages/context/package.json
packages/ui/package.json
pnpm-lock.yaml

Relates to https://github.com/prax-wallet/registry/issues/60

feat(extension): display images for registry frontends

---

packages/ui/components/ui/tx/action-view.tsx
packages/ui/components/ui/tx/actions-views/delegator-vote.tsx
packages/ui/components/ui/tx/actions-views/validator-vote.tsx

Mirrors https://github.com/penumbra-zone/web/pull/1578

Additional tx classifications

---

package.json
packages/eslint-config/package.json
pnpm-lock.yaml
turbo.json

Closes https://github.com/penumbra-zone/web/issues/1669

Update turbo dep to 2.0

---

apps/extension/package.json
packages/context/package.json
packages/ui/package.json
pnpm-lock.yaml

related: https://github.com/prax-wallet/registry/pull/89

update to 11.2 registry

---

.github/ISSUE_TEMPLATE/deployment.md

Closes https://github.com/prax-wallet/prax/issues/146

Enumerate userflows for release testing

---

apps/extension/webpack.config.ts

The latest change in #209 actually broke things... That's an urgent fix

fix: stringify the extension id correctly

---

apps/extension/src/content-scripts/injected-penumbra-global.ts

references https://github.com/prax-wallet/prax/issues/175

remove inject request method

---

apps/extension/src/wallet-services.ts

follow up from the https://github.com/prax-wallet/prax/pull/217#discussion_r1810218025

fix(extension): typesafe storage clearing

---

apps/extension/package.json
packages/context/package.json
packages/ui/package.json
pnpm-lock.yaml

Relates to https://github.com/prax-wallet/registry/pull/108
Makes registry parsing of metadata to be forward compatible.

Update registry to latest

---

apps/extension/package.json
apps/extension/public/beta-manifest.json
apps/extension/public/manifest.json

npm deps were updated in the previous release and are already up to date.
currently testing, optimistically requesting review @hdevalence

prep v14.2 release

---

apps/extension/src/content-scripts/injected-penumbra-global.ts

Reverts prax-wallet/prax#213
Issue persists. Cannot remove this until chain upgrade.

Revert "remove inject request method"

---

apps/extension/src/routes/popup/home/validate-address/result.tsx

Closes https://github.com/prax-wallet/prax/issues/243

Update account terminology

---

apps/extension/package.json
apps/extension/src/routes/page/onboarding/password/utils.ts
packages/context/package.json
packages/ui/package.json
pnpm-lock.yaml

defaults to RC-hosted `https://app.penumbra.zone/` frontend during onboarding
-------------
https://github.com/user-attachments/assets/f2442780-6a4d-4bb0-a1a4-18f43cb76199
---------------
-------------------

registry: default frontend selection

---

apps/extension/src/content-scripts/injected-listeners.ts
apps/extension/src/senders/approve.ts
apps/extension/src/senders/internal.ts
apps/extension/src/senders/session.ts
apps/extension/src/senders/validate.ts
apps/extension/src/service-worker.ts

fulfills new api from
passing CI requires release of https://github.com/penumbra-zone/web/pull/2034

session client reconnect

---

apps/extension/src/wallet-services.ts

fix `getChainId` startup request

---

packages/noble/package.json
pnpm-lock.yaml

define peer deps of `@repo/noble` package so pnpm calms down

chore: correct noble peers

---

apps/extension/webpack.config.ts

alternatively, this could be parameterized

chore: correct webext starturl (http, not https)

---

.changeset/chatty-apes-drive.md
apps/extension/src/approve-transaction.ts
apps/extension/src/entry/popup-root.tsx
apps/extension/src/hooks/popup-ready.ts
apps/extension/src/message/listen-popup.ts
apps/extension/src/message/listen-ready.ts
apps/extension/src/message/popup.ts
apps/extension/src/message/send-popup.ts
apps/extension/src/popup.ts
apps/extension/src/senders/approve.test.ts
apps/extension/src/senders/approve.ts
apps/extension/src/senders/internal.ts
apps/extension/src/state/index.ts
apps/extension/src/state/origin-approval.test.ts
apps/extension/src/state/origin-approval.ts
apps/extension/src/state/tx-approval.test.ts
apps/extension/src/state/tx-approval.ts
apps/extension/src/utils/chrome-errors.ts

reviewed in chunks, staging here.
rescoped into https://github.com/prax-wallet/prax/pull/318
rescoped into https://github.com/prax-wallet/prax/pull/318

messaging refactor staging

---

apps/extension/src/content-scripts/injected-penumbra-global.ts

references https://github.com/prax-wallet/prax/issues/175

remove minifront workaround

---

apps/extension/src/routes/page/onboarding/constants.ts
apps/extension/src/routes/page/onboarding/success.tsx

precursor to https://github.com/prax-wallet/prax/pull/365 that will be folded in.
--------------
https://github.com/user-attachments/assets/146e7dd9-8e6e-4e5f-834e-7fdcc8bd11f8

onboarding: redirect to landing page

---

apps/extension/package.json
package.json
packages/context/package.json
packages/ui/components/ui/tx/action-view.tsx
packages/ui/components/ui/tx/actions-views/position-open-view.tsx
packages/ui/package.json
pnpm-lock.yaml

pairs with https://github.com/penumbra-zone/web/pull/2626

action views: encrypted position metadata support

---

packages/noble/package.json
pnpm-lock.yaml

chore: bump stargate
